# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pysymba_dev',
                'doc_host': 'https://mgm79.github.io',
                'git_url': 'https://github.com/mgm79/pysymba_dev',
                'lib_path': 'pysymba_dev'},
  'syms': {'pysymba_dev.core': {'pysymba_dev.core.foo': ('core.html#foo', 'pysymba_dev/core.py')}}}
